name: Scrape Gas Prices

on:
  schedule:
    # Runs at 12:00 UTC every day
    - cron: '0 12 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run scraper
      run: python scraper.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add -A
        git commit -m "Update gas prices" -a || echo "No changes to commit"
        git push
